dist: trusty
language: python
sudo: false
python:
  - 2.7.14

branches:
  only:
  - master

env:
  matrix:
    # This environment tests the newest supported anaconda env
    - DISTRIB="conda" PYTHON_VERSION="2.7"
      NUMPY_VERSION="1.10.4" SCIPY_VERSION="0.16.1"
      SIX_VERSION="1.10.0" COVERAGE="true"
    - DISTRIB="conda" PYTHON_VERSION="3.5"
      NUMPY_VERSION="1.10.4" SCIPY_VERSION="0.16.1"
      SIX_VERSION="1.10.0" COVERAGE="true"

    # # This environment tests conda extras skmonaco and matplotlib
    # - DISTRIB="conda_extra" PYTHON_VERSION="3.5"
    #   NUMPY_VERSION="1.10.4" SCIPY_VERSION="0.16.1"
    #   SIX_VERSION="1.10.0" COVERAGE="true"

    # This environment tests minimal dependency versions
    - DISTRIB="conda_min" PYTHON_VERSION="2.7"
      SIX_VERSION="1.10.0" NUMPY_VERSION="1.10.4" SCIPY_VERSION="0.16.1"
      COVERAGE="true"
    - DISTRIB="conda_min" PYTHON_VERSION="3.4"
      SIX_VERSION="1.10.0" NUMPY_VERSION="1.10.4" SCIPY_VERSION="0.16.1"
      COVERAGE="true"

    # basic Ubuntu build environment
    - DISTRIB="ubuntu" PYTHON_VERSION="2.7"
      NUMPY_VERSION="1.14.0" SCIPY_VERSION="0.14.0" SIX_VERSION="1.10.0"
      COVERAGE="true"

    # - DISTRUB="ubuntu_extra" PYTHON_VERSION="2.7"
    #   SKMONACO_VERSION="0.2" NUMPY_VERSION="1.13.0" SCIPY_VERSION="1.0.0"
    #   MATPLOTLIB_VERSION="0.99"  SIX_VERSION="1.10.0" COVERAGE="true"

# Turn off notifications
notifications:
  email: false

# command to install dependencies
install: source continuous_integration/install.sh
# command to run tests
script: bash continuous_integration/test_script.sh
after_success:
- if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
  
